<template>
  <div v-if="exam" class="paper-builder">
    <PageContainer>
      <PageHeader
        title="试卷编辑"
        :description="paperReadOnly ? '当前试卷已冻结或考试已撤销，题目不可再增删。' : '左侧为科目题库，右侧为当前试卷题目。'"
      >
        <template #actions>
          <el-button @click="router.push(examListPath)">返回考试列表</el-button>

          <el-tooltip
            v-if="paperReadOnly"
            content="试卷已冻结或考试已撤销，不可再自动组卷"
            placement="bottom"
          >
            <span>
              <el-button type="primary" plain disabled>自动组卷</el-button>
            </span>
          </el-tooltip>
          <el-button
            v-else
            type="primary"
            plain
            :disabled="operating"
            @click="openAutoGenerateDialog"
          >
            自动组卷
          </el-button>

          <el-tooltip v-if="paperReadOnly" content="试卷已冻结或考试已撤销，不可再改题" placement="bottom">
            <span>
              <el-button type="danger" plain disabled>清空试卷</el-button>
            </span>
          </el-tooltip>
          <el-button
            v-else
            type="danger"
            plain
            :loading="operating"
            :disabled="operating"
            @click="handleClearPaper"
          >
            清空试卷
          </el-button>
        </template>
      </PageHeader>

      <ExamMetaPanel :exam="examForPanel" />

      <div class="builder-summary">
        <StatusCard label="题库题量" :value="totals.available" hint="按当前考试科目加载" />
        <StatusCard label="已选题量" :value="totals.selected" hint="每次增删题后立即刷新" />
        <StatusCard label="试卷总分" :value="paperScore" hint="按题目数量自动更新总分" />
        <StatusCard label="当前状态" :value="builderStatusLabel" :hint="builderStatusHint" />
      </div>

      <el-input
        v-model="keyword"
        placeholder="按题干或章节筛选当前页面题目"
        clearable
      />
    </PageContainer>

    <div class="builder-grid">
      <PaperBuilderPanel
        title="科目题库"
        description="可将题目加入当前试卷。"
        :count="totals.available"
      >
        <div class="panel-groups">
          <PaperQuestionGroup
            v-for="item in availableGroups"
            :key="`available-${item.type}`"
            :title="item.title"
            :description="item.description"
            :questions="item.questions"
            :type="item.type"
            :disabled-ids="selectedIds[item.type]"
            action-text="加入试卷"
            :action-loading="operating"
            :action-disabled="operating"
            :show-action="!paperReadOnly"
            empty-text="当前科目下暂无此题型题目"
            @action="handleAddQuestion"
          />
        </div>
      </PaperBuilderPanel>

      <PaperBuilderPanel
        title="当前试卷"
        description="可将题目从试卷中移出。"
        :count="totals.selected"
      >
        <div class="panel-groups">
          <PaperQuestionGroup
            v-for="item in selectedGroups"
            :key="`selected-${item.type}`"
            :title="item.title"
            :description="item.description"
            :questions="item.questions"
            :type="item.type"
            action-text="移出试卷"
            :action-loading="operating"
            :action-disabled="operating"
            :show-action="!paperReadOnly"
            empty-text="当前试卷下暂无此题型题目"
            @action="handleRemoveQuestion"
          />
        </div>
      </PaperBuilderPanel>
    </div>

    <el-dialog v-model="autoGenerateVisible" title="自动组卷" width="520px">
      <el-alert
        title="自动组卷会清空当前试卷，并按设定数量重新抽题。"
        type="warning"
        show-icon
        :closable="false"
      />

      <el-form class="auto-form" label-position="top">
        <el-form-item label="当前考试科目">
          <el-input :model-value="autoGenerateForm.subject" disabled />
        </el-form-item>
        <div class="auto-form__grid">
          <el-form-item label="选择题数量">
            <el-input-number v-model="autoGenerateForm.changeNumber" :min="0" :max="100" />
          </el-form-item>
          <el-form-item label="填空题数量">
            <el-input-number v-model="autoGenerateForm.fillNumber" :min="0" :max="100" />
          </el-form-item>
          <el-form-item label="判断题数量">
            <el-input-number v-model="autoGenerateForm.judgeNumber" :min="0" :max="100" />
          </el-form-item>
        </div>
      </el-form>

      <div class="auto-summary">
        <span>预计题量：{{ autoGenerateTotal }}</span>
        <span>预计总分：{{ autoGenerateTotal * 2 }}</span>
      </div>

      <template #footer>
        <el-button @click="autoGenerateVisible = false">取消</el-button>
        <el-button type="primary" :loading="operating" @click="handleAutoGenerate">
          确认组卷
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import dayjs from 'dayjs'
import PageContainer from '@/components/common/PageContainer.vue'
import PageHeader from '@/components/common/PageHeader.vue'
import StatusCard from '@/components/common/StatusCard.vue'
import ExamMetaPanel from '@/components/exam/ExamMetaPanel.vue'
import PaperBuilderPanel from '@/components/exam/PaperBuilderPanel.vue'
import PaperQuestionGroup from '@/components/exam/PaperQuestionGroup.vue'
import { getExamById } from '@/api/examApi'
import {
  addPaperQuestion,
  autoGeneratePaper,
  clearPaper,
  getPaper,
  getPaperScore,
  getPracticeBySubject,
  removePaperQuestion
} from '@/api/paperApi'
import { usePaperBuilder } from '@/composables/usePaperBuilder'
import { getSession } from '@/utils/auth'
import { buildConsolePath, QUESTION_TYPE_OPTIONS } from '@/utils/constants'
import { formatDateTime } from '@/utils/date'

const route = useRoute()
const router = useRouter()
const consoleRole = getSession()?.role
const exam = ref(null)
const paperScore = ref(0)
const keyword = ref('')
const operating = ref(false)
const autoGenerateVisible = ref(false)
const examListPath = buildConsolePath(consoleRole, 'exams')

const autoGenerateForm = reactive({
  subject: '',
  changeNumber: 0,
  fillNumber: 0,
  judgeNumber: 0
})

const paperReadOnly = computed(
  () => !!(exam.value?.paperLocked || exam.value?.revokedAt)
)

const autoGenerateTotal = computed(() =>
  Number(autoGenerateForm.changeNumber || 0) +
  Number(autoGenerateForm.fillNumber || 0) +
  Number(autoGenerateForm.judgeNumber || 0)
)

const builderStatusLabel = computed(() => {
  if (exam.value?.revokedAt) {
    return '已撤销'
  }
  if (exam.value?.paperLocked) {
    return '已冻结'
  }
  return '可编辑'
})

const builderStatusHint = computed(() => {
  if (exam.value?.revokedAt) {
    return exam.value.revokeReason || '本场考试已撤销，不再支持组卷和改题。'
  }
  if (exam.value?.paperLocked) {
    return '试卷已进入冻结窗口，仅可查看当前内容。'
  }
  return `预计 ${formatDateTime(buildFreezeAt(exam.value))} 进入冻结窗口。`
})

const examForPanel = computed(() => {
  if (!exam.value) {
    return null
  }

  return {
    ...exam.value,
    freezeAt: buildFreezeAt(exam.value),
    windowEndAt: buildWindowEndAt(exam.value)
  }
})

const {
  availableQuestions,
  selectedQuestions,
  totals,
  setAvailableQuestions,
  setSelectedQuestions,
  hasQuestion
} = usePaperBuilder()

const selectedIds = computed(() => ({
  1: selectedQuestions.value[1].map((item) => item.questionId),
  2: selectedQuestions.value[2].map((item) => item.questionId),
  3: selectedQuestions.value[3].map((item) => item.questionId)
}))

function buildFreezeAt(currentExam) {
  if (!currentExam?.examDate) {
    return ''
  }
  const examDate = dayjs(currentExam.examDate)
  if (!examDate.isValid()) {
    return ''
  }
  return examDate.subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss')
}

function buildWindowEndAt(currentExam) {
  if (!currentExam?.examDate) {
    return ''
  }
  const examDate = dayjs(currentExam.examDate)
  if (!examDate.isValid()) {
    return ''
  }
  return examDate
    .add(Number(currentExam.totalTime || 0), 'minute')
    .format('YYYY-MM-DD HH:mm:ss')
}

function matchKeyword(question) {
  const safeKeyword = keyword.value.trim().toLowerCase()
  if (!safeKeyword) {
    return true
  }
  return [question.question, question.section, question.analysis]
    .filter(Boolean)
    .some((field) => String(field).toLowerCase().includes(safeKeyword))
}

const availableGroups = computed(() =>
  QUESTION_TYPE_OPTIONS.map((item) => ({
    type: item.value,
    title: item.label,
    description: `科目题库中的${item.label}`,
    questions: availableQuestions.value[item.value].filter(matchKeyword)
  }))
)

const selectedGroups = computed(() =>
  QUESTION_TYPE_OPTIONS.map((item) => ({
    type: item.value,
    title: item.label,
    description: `当前试卷中的${item.label}`,
    questions: selectedQuestions.value[item.value].filter(matchKeyword)
  }))
)

async function fetchExam() {
  const response = await getExamById(route.params.examCode)
  if (response.code !== 200 || !response.data) {
    throw new Error(response.message || '获取考试信息失败')
  }
  exam.value = response.data
}

async function fetchPracticeQuestions() {
  const response = await getPracticeBySubject(exam.value.source)
  if (response.code === 200) {
    setAvailableQuestions(response.data)
    return
  }
  ElMessage.warning(response.message || '题库数据加载不完整')
}

async function fetchPaperData() {
  const [paperResponse, scoreResponse] = await Promise.all([
    getPaper(exam.value.paperId),
    getPaperScore(exam.value.paperId)
  ])

  if (paperResponse.code === 200) {
    setSelectedQuestions(paperResponse.data)
  }

  if (scoreResponse.code === 200) {
    paperScore.value = scoreResponse.data || 0
    if (exam.value) {
      exam.value.totalScore = paperScore.value
    }
  }
}

async function refreshBuilderData() {
  try {
    await fetchExam()
    await fetchPracticeQuestions()
    await fetchPaperData()
  } catch (error) {
    ElMessage.error(error.message || '获取试卷信息失败，请稍后重试')
  }
}

function openAutoGenerateDialog() {
  autoGenerateForm.subject = exam.value?.source || ''
  autoGenerateForm.changeNumber = selectedQuestions.value[1].length
  autoGenerateForm.fillNumber = selectedQuestions.value[2].length
  autoGenerateForm.judgeNumber = selectedQuestions.value[3].length
  autoGenerateVisible.value = true
}

function validateAutoGenerateForm() {
  if (!autoGenerateForm.subject.trim()) {
    ElMessage.warning('当前考试未配置科目，无法自动组卷')
    return false
  }

  if (autoGenerateTotal.value <= 0) {
    ElMessage.warning('请至少填写一种题型数量')
    return false
  }

  return true
}

async function handleAutoGenerate() {
  if (paperReadOnly.value || operating.value) {
    return
  }

  if (!validateAutoGenerateForm()) {
    return
  }

  operating.value = true
  try {
    const response = await autoGeneratePaper({
      paperId: exam.value.paperId,
      subject: autoGenerateForm.subject.trim(),
      changeNumber: Number(autoGenerateForm.changeNumber || 0),
      fillNumber: Number(autoGenerateForm.fillNumber || 0),
      judgeNumber: Number(autoGenerateForm.judgeNumber || 0)
    })

    if (response.code === 200) {
      ElMessage.success(response.message || '试卷组卷成功')
      autoGenerateVisible.value = false
      await refreshBuilderData()
      return
    }

    ElMessage.error(response.message || '自动组卷失败')
  } catch (error) {
    const message = error?.response?.data?.message
    ElMessage.error(message || '自动组卷失败，请稍后重试')
  } finally {
    operating.value = false
  }
}

async function handleAddQuestion({ type, question }) {
  if (paperReadOnly.value || operating.value) {
    return
  }
  if (hasQuestion(type, question.questionId)) {
    ElMessage.warning('这道题已经在当前试卷中')
    return
  }

  operating.value = true
  try {
    const response = await addPaperQuestion({
      paperId: exam.value.paperId,
      questionType: type,
      questionId: question.questionId
    })

    if (response.code === 200) {
      ElMessage.success('题目已加入试卷')
      await fetchPaperData()
      return
    }

    ElMessage.error(response.message || '加入试卷失败')
  } catch (error) {
    const message = error?.response?.data?.message
    ElMessage.error(message || '加入试卷失败，请稍后重试')
  } finally {
    operating.value = false
  }
}

async function handleRemoveQuestion({ type, question }) {
  if (paperReadOnly.value || operating.value) {
    return
  }

  operating.value = true
  try {
    const response = await removePaperQuestion(exam.value.paperId, type, question.questionId)
    if (response.code === 200) {
      ElMessage.success('题目已从试卷移除')
      await fetchPaperData()
      return
    }
    ElMessage.error(response.message || '移出试卷失败')
  } catch (error) {
    const message = error?.response?.data?.message
    ElMessage.error(message || '移出试卷失败，请稍后重试')
  } finally {
    operating.value = false
  }
}

async function handleClearPaper() {
  if (paperReadOnly.value || operating.value) {
    return
  }
  try {
    await ElMessageBox.confirm('确认清空整张试卷吗？该操作无法恢复。', '清空试卷', {
      type: 'warning'
    })
  } catch (error) {
    return
  }

  operating.value = true
  try {
    const response = await clearPaper(exam.value.paperId)
    if (response.code === 200) {
      ElMessage.success('试卷已清空')
      await fetchPaperData()
      return
    }
    ElMessage.error(response.message || '清空试卷失败')
  } catch (error) {
    const message = error?.response?.data?.message
    ElMessage.error(message || '清空试卷失败，请稍后重试')
  } finally {
    operating.value = false
  }
}

onMounted(refreshBuilderData)
</script>

<style scoped>
.paper-builder {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.builder-summary {
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  margin: 20px 0;
}

.builder-grid {
  display: grid;
  gap: 20px;
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.panel-groups {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.auto-form {
  margin-top: 18px;
}

.auto-form__grid {
  display: grid;
  gap: 0 16px;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
}

.auto-summary {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  margin-top: 8px;
  color: var(--text-secondary);
}

@media (max-width: 1100px) {
  .builder-grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 768px) {
  .auto-summary {
    flex-direction: column;
  }
}
</style>
